default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: personal-site_development

test:
  <<: *default
  database: personal-site_test

production:
  <<: *default
  database: personal-site_production
  username: personal-site
  password: <%= ENV['PERSONAL-SITE_DATABASE_PASSWORD'] %>
